version: "3.9"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - API_URL=https://gbfs.urbansharing.com/oslobysykkel.no/station_information.json
      - COMPOSE_PROJECT_NAME=OrigoAPI